version: "3"

services:
    web:
        image: chengtze/timelink_web
        volumes:
            - ./instance:/usr/src/instance
            - ./logs:/usr/src/logs
        environment:
            - TZ="Asia/Taipei"
        working_dir: /usr/src
        command: gunicorn -c ./timelink/gunicorn.conf.py 'timelink:create_app()'

    # socket-server:

    linebot:
        image: chengtze/timelink_bot
        env_file:
            - ./.env
        environment:
            - TZ="Asia/Taipei"
        command: gunicorn -w 2 -b :5000 app:timelink_bot