version: "3.3"

services:
    taipei_oneday:
        image: chengtze/taipei_oneday
        env_file:
            - ./taipei_oneday/.env
        environment:
            - TZ="Asia/Taipei"
        volumes:
            - ./certificate.crt:/etc/ssl/certificate.crt
            - ./private.key:/etc/ssl/private.key
        ports:
            - "3000:3000"
        command: gunicorn -w 2 -b :3000 app:app

    timelink_web:
        image: chengtze/timelink_web
        volumes:
            - ./instance:/usr/src/instance
        environment:
            - TZ="Asia/Taipei"
        ports:
            - "8000:8000"
        working_dir: /usr/src
        command: gunicorn -c ./timelink/gunicorn.conf.py 'timelink:create_app() -D'

    timelink_bot:
        image: chengtze/timelink_bot
        env_file:
            - ./.env
        environment:
            - TZ="Asia/Taipei"
        ports:
            - "5000:5000"
        command: gunicorn -w 2 -b :5000 app:timelink_bot

    nginx:
        image: chengtze/timelink_nginx
        environment:
            - TZ="Asia/Taipei"
        volumes:
            - ./certificate.crt:/etc/ssl/certificate.crt
            - ./private.key:/etc/ssl/private.key
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - taipei_oneday
            - timelink_web
            - timelink_bot
