version: "3.3"

services:
    timelink_web:
        image: chengtze/timelink_web
        env_file:
            - ./.env
        environment:
            - TZ="Asia/Taipei"
        ports:
            - "8000:8000"
        command: gunicorn -w 2 -b :8000 wsgi:app

    timelink_bot:
        image: chengtze/timelink_bot
        env_file:
            - ./.env
        environment:
            - TZ="Asia/Taipei"
        ports:
            - "5000:5000"
        command: gunicorn -w 2 -b :5000 app:linebot

    nginx:
        image: chengtze/timelink_nginx
        environment:
            - TZ="Asia/Taipei"
        volumes:
            - ./certificate.crt:/etc/ssl/certificate.crt
            - ./private.key:/etc/ssl/private.key
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - timelink_web
            - timelink_bot
