version: "3"

services:
  web_api:
    build:
      context: ./web_api
      dockerfile: Dockerfile
    image: changtze/web_api:0.0.1-alpha
    container_name: web_api
    ports:
      - "8000:8000"
    volumes:
      - ./web_api/app/configs/config.py:/usr/src/app/configs/config.py
      - ./logs/web_api:/usr/src/app/logs
    restart: unless-stopped
