version: "3.3"

services:
    taipei_oneday:
        image: chengtze/taipei_oneday
        env_file:
            - ./taipei_oneday/.env
        environment:
            - TZ="Asia/Taipei"
        volumes:
            - ./certificate.crt:/etc/ssl/certificate.crt
            - ./private.key:/etc/ssl/private.key
        command: gunicorn -w 2 -b :3000 app:app

    timelink_web:
        image: chengtze/timelink_web
        volumes:
            - ./instance:/usr/src/instance
            - ./logs:/usr/src/logs
        environment:
            - TZ="Asia/Taipei"
        working_dir: /usr/src
        command: gunicorn -c ./timelink/gunicorn.conf.py 'timelink:create_app()'

    timelink_bot:
        image: chengtze/timelink_bot
        env_file:
            - ./.env
        environment:
            - TZ="Asia/Taipei"
        command: gunicorn -w 2 -b :5000 app:timelink_bot

    nginx:
        image: chengtze/timelink_nginx
        environment:
            - TZ="Asia/Taipei"
        volumes:
            - ./certificate.crt:/etc/ssl/certificate.crt
            - ./private.key:/etc/ssl/private.key
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - taipei_oneday
            - timelink_web
            - timelink_bot
