"""Add owner id on Group table

Revision ID: 2c89ab87c121
Revises: 703fc751ce24
Create Date: 2024-01-22 17:18:51.422977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c89ab87c121"
down_revision: Union[str, None] = "703fc751ce24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("line_group", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "line_group", "user_account", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "line_group", type_="foreignkey")
    op.drop_column("line_group", "owner_id")
    # ### end Alembic commands ###
