"""Change data type on working_hour

Revision ID: 5c28b00efde3
Revises: 05e9bf71b8b7
Create Date: 2023-12-28 17:33:09.624984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c28b00efde3"
down_revision: Union[str, None] = "05e9bf71b8b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "working_hour",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False,
    )
    op.alter_column(
        "working_hour",
        "end_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "working_hour",
        "end_time",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "working_hour",
        "start_time",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
