"""Add id on service_user and  nullable

Revision ID: abbcc0b41caf
Revises: ace146ed185b
Create Date: 2024-01-16 15:54:56.283961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abbcc0b41caf"
down_revision: Union[str, None] = "ace146ed185b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_user_account", sa.Column("id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_user_account", "id")
    # ### end Alembic commands ###
