FROM python:3.12-slim

WORKDIR /usr/src
COPY requirements.txt .
RUN apt-get update && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -rf requirements.txt && \
    rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Taipei 

COPY gunicorn.local-dev.conf.py .
COPY app app

EXPOSE 8000
ENV PORT 8000
ENTRYPOINT ["gunicorn" , "-c", "gunicorn.local-dev.conf.py"]