"""Change Role name

Revision ID: 122e184725c9
Revises: d3f269ea1032
Create Date: 2024-01-02 15:46:21.184361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122e184725c9'
down_revision: Union[str, None] = 'd3f269ea1032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.Enum('ADMIN', 'GROUP_OWNER', 'GROUP_MEMBER', name='rolename'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
