"""Add description column for Service table

Revision ID: 19fdd907fd45
Revises: e998d1c07689
Create Date: 2023-12-24 15:53:18.665502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fdd907fd45'
down_revision: Union[str, None] = 'e998d1c07689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'description')
    # ### end Alembic commands ###
