"""Change primary_key on service_user

Revision ID: 1e9ba2418e7f
Revises: abbcc0b41caf
Create Date: 2024-01-16 15:56:50.969181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9ba2418e7f'
down_revision: Union[str, None] = 'abbcc0b41caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
