"""Add Role table fix nullable.

Revision ID: 548d9e81facc
Revises: 5c28b00efde3
Create Date: 2024-01-02 15:30:29.541766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548d9e81facc'
down_revision: Union[str, None] = '5c28b00efde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'GROUP_ADMIN', 'GROUP_MEMBER', name='rolename'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_account', sa.Column('role_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_account', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###
