"""Add owner id on Service table

Revision ID: 752f53c96edd
Revises: 2c89ab87c121
Create Date: 2024-01-23 18:31:56.893625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "752f53c96edd"
down_revision: Union[str, None] = "2c89ab87c121"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "service", "user_account", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service", type_="foreignkey")
    op.drop_column("service", "owner_id")
    # ### end Alembic commands ###
